// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2D1HqP36-WRMJYpAcTNzk69IvWPzYqXM',
    appId: '1:952089546214:web:12a73bf57ded8aa4425a27',
    messagingSenderId: '952089546214',
    projectId: 'ai-study-notes-app-96164',
    authDomain: 'ai-study-notes-app-96164.firebaseapp.com',
    storageBucket: 'ai-study-notes-app-96164.firebasestorage.app',
    measurementId: 'G-V5B3Z3TGF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAlxxOZ1wgr7qE8oFsk9IGJ6_Tceq2Kn0',
    appId: '1:952089546214:android:e00226b70f84b010425a27',
    messagingSenderId: '952089546214',
    projectId: 'ai-study-notes-app-96164',
    storageBucket: 'ai-study-notes-app-96164.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5M-ZYHf4-VHezi1rzsJhj8MKFZJSYzIo',
    appId: '1:952089546214:ios:650c1b2849d5ecec425a27',
    messagingSenderId: '952089546214',
    projectId: 'ai-study-notes-app-96164',
    storageBucket: 'ai-study-notes-app-96164.firebasestorage.app',
    androidClientId: '952089546214-o25nicipjbr95trdu0q5ht04e1cqr88j.apps.googleusercontent.com',
    iosClientId: '952089546214-deo2f6oovj5f4dtjpmb3baidusgn2md9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiStudyNotes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5M-ZYHf4-VHezi1rzsJhj8MKFZJSYzIo',
    appId: '1:952089546214:ios:650c1b2849d5ecec425a27',
    messagingSenderId: '952089546214',
    projectId: 'ai-study-notes-app-96164',
    storageBucket: 'ai-study-notes-app-96164.firebasestorage.app',
    androidClientId: '952089546214-o25nicipjbr95trdu0q5ht04e1cqr88j.apps.googleusercontent.com',
    iosClientId: '952089546214-deo2f6oovj5f4dtjpmb3baidusgn2md9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiStudyNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2D1HqP36-WRMJYpAcTNzk69IvWPzYqXM',
    appId: '1:952089546214:web:52194be6a86ac4bc425a27',
    messagingSenderId: '952089546214',
    projectId: 'ai-study-notes-app-96164',
    authDomain: 'ai-study-notes-app-96164.firebaseapp.com',
    storageBucket: 'ai-study-notes-app-96164.firebasestorage.app',
    measurementId: 'G-E7YW3RYSJM',
  );
}
